export const sellers = [
  {
    SellerName: 'Esthera Jackson',
    UID: 'UID001',
    Gender: 'Nam',
    Age: 21,
    Email: 'esthera@simmmple.com',
  },
  {
    SellerName: 'Esthera Jackson',
    UID: 'UID001',
    Gender: 'Nam',
    Age: 21,
    Email: 'estheruulisimmimple.com',
  },
  {
    SellerName: 'Esthera Jackson',
    UID: 'UID001',
    Gender: 'Nam',
    Age: 21,
    Email: 'estheragisimimple.com',
  },
  {
    SellerName: 'Esthera Jackson',
    UID: 'UID001',
    Gender: 'Nam',
    Age: 21,
    Email: 'estherasimmmple.com',
  },
  {
    SellerName: 'Esthera Jackson',
    UID: 'UID002',
    Gender: 'Nữ',
    Age: 22,
    Email: 'estherasimple@gmail.com',
  },
  {
    SellerName: 'John Doe',
    UID: 'UID003',
    Gender: 'Nam',
    Age: 30,
    Email: 'johndoe@example.com',
  },
  {
    SellerName: 'Jane Doe',
    UID: 'UID004',
    Gender: 'Nữ',
    Age: 28,
    Email: 'janedoe@example.com',
  },
  {
    SellerName: 'Michael Smith',
    UID: 'UID005',
    Gender: 'Nam',
    Age: 40,
    Email: 'michael.smith@work.com',
  },
  {
    SellerName: 'Sarah Jones',
    UID: 'UID006',
    Gender: 'Nữ',
    Age: 35,
    Email: 'sarah.jones@home.net',
  },
  {
    SellerName: 'David Brown',
    UID: 'UID007',
    Gender: 'Nam',
    Age: 25,
    Email: 'david.brown@school.edu',
  },
];
